# gpt-4-turbo-2024-04-09:
#     model_name: gpt-4-turbo-2024-04-09
#     endpoints: null
#     api_type: openai
quest-rm:
    model_name: quest-rm
    beautiful_name: Quest-RM
    endpoints:
        api_base: http://127.0.0.1:5002/analyze
    api_type: thesis